core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('SB', 'Shirts And Blouses'),
    ('TS', 'T-Shirts'),
    ('SK', 'Skirts'),
    ('HS', 'Hoodies&Sweatshirts')
)

LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'BillingAddress', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a BillingAddress
    (Failed Checkout)
    3. Payment
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'BillingAddresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% load slide_template_tags %}
{% block content %}
<style>
	/*[ Block2 ]
///////////////////////////////////////////////////////////
*/
.block2-labelpromotion::before,
.block2-labelsale::before,
.block2-labelnew::before 
{
  z-index: 100;
  font-family: Montserrat-Regular;
  font-size: 12px;
  color: white;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 22px;
  border-radius: 11px;
  position: absolute;
  top: 12px;
  left: 12px;
}

.block2-labelsale::before {
  background-color: white;
  color: #000;
  content: 'Sale';
}

.block2-labelnew::before {
  background-color: #007bff;
  content: 'New';
}

.block2-labelpromotion::before{
	background-color: #000;
	content: 'Promotion';
	width: 70px;
  }

  .btn-dark {
    color: #fff;
    background-color: #000;
    border-color: #000;
}

.btn-outline-dark {
    color: #000;
    border-color: #000;
}


</style>

	<!-- Slide1 -->
	<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">

				{% slides %}

				<!-- <div class="item-slick1 item2-slick1" style="background-image: url({% static 'images/master-slide-03.webp' %});">-->
<!--					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">-->
<!--						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="rollIn">-->
<!--							Women Collection 2018-->
<!--						</span>-->
<!--						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="lightSpeedIn">-->
<!--							New arrivals-->
<!--						</h2>-->
<!--						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="slideInUp">-->
<!--							&lt;!&ndash; Button &ndash;&gt;-->
<!--							<a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">-->
<!--								Shop Now-->
<!--							</a>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div> -->

			</div>
		</div>
	</section>

	<!-- Category start -->
	<style>
		.hov1{
			background-color: white !important;
			color: black !important;
			
		}
	</style>
	<section class="banner bgwhite p-t-40 p-b-40">
		<div class="container">
			<div class="row">

				{% categories_div %}

<!--				<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">-->
<!--					-->
<!--					<div class="block1 hov-img-zoom pos-relative m-b-30">-->
<!--						<img src="{% static 'images/banner-02.webp' %}" alt="IMG-BENNER">-->
<!--						<div class="block1-wrapbtn w-size2">-->
<!--							<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">-->
<!--								Dresses-->
<!--							</a>-->
<!--						</div>-->
<!--					</div>-->
<!--					-->
<!--					<div class="block1 hov-img-zoom pos-relative m-b-30">-->
<!--						<img src="{% static 'images/banner-05.webp' %}" alt="IMG-BENNER">-->
<!--						<div class="block1-wrapbtn w-size2">-->
<!--							<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">-->
<!--								Sunglasses-->
<!--							</a>-->
<!--						</div>-->
<!--					</div>-->
<!--					-->
<!--				</div>-->




			</div>
		</div>
	</section>

	<!-- New Product -->
	<style>
		.newproduct{
			margin-bottom: 2px;
			padding-bottom: 2px;
		}
	</style>
	<section class="newproduct bgwhite p-t-45 p-b-105">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Featured Products
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">

					{% for item in object_list %}
					
					<div class="item-slick2 p-l-15 p-r-15">
						<!-- Block2 -->
						<div class="block2">
							
							<div class="block2-img wrap-pic-w of-hidden pos-relative block2-label{{item.get_label_display}}">
								<a href="{{item.get_absolute_url}}">
								<img src="{{ item.image.url }}" alt="IMG-PRODUCT" 
								style="height: 370px; width:100%; "></a>
							   

								<!-- <div class="block2-overlay trans-0-4">
									<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
										<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
										<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
									</a>
	
									
								</div> -->
							</div>
							

							<div class="block2-txt p-t-20">
								<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5" style="color: black;">
									{{ item.title }}
								</a>

								{% if item.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="color: black;">
									${{ item.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5">
									${{ item.discount_price }}
								</span>
								{% else %}
								<span class="block2-price m-text6 p-r-5" style="color: black;">
									${{ item.price }}
								</span>
								{% endif %}
								

								
							</div>
							
						</div>
					</div>
				
					{% endfor %}

					
				
				</div>
			</div>

		</div>
	</section>

	<!-- ------------------Banner2  start ------------------------>
	<style>
		.banner2{
			background-color: #fff;
			margin-right: 1rem;
			margin-left: 1rem;
			margin-bottom: 0 !important;
			padding-bottom: 0 !important;
		}

		.ban_img{
			height: 680px;
			width: 100%;
		}
		.ban5_img{
			height: 580px;
			width: 100%;
		}

		.btn-light {
			color: #000;
			background-color: #fff;
			border-color: #fff;
			border-radius: 20px;
		}
		.wrap-btn-slide1 a:hover{
			background-color: whitesmoke;
			color: #000 !important;
			opacity: 0.7;
	
		}
	</style>
	<section class="banner2 bg5 p-t-55 p-b-55">
		<h4 style="font-weight: 500;">Season's Essentials</h4>
		<div class="">
			<div class="row">
				<div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_700,c_limit/c85699cb-2813-4acd-8822-c3344fe07f17/nike-just-do-it.jpg" alt="IMG-BANNER" class="ban_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<span class="m-text9 p-t-45 fs-20-sm">
								Bold, Brights Looks
							</span>

							<br>
							

								<div class="wrap-btn-slide1 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite  trans-0-4">
								Shop Now
							</a>
						</div>

						</div>
					</div>
				</div>

				<div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_700,c_limit/3d8a771b-0fd0-49b0-a9ad-1c688b192bf9/nike-just-do-it.jpg"  alt="IMG-BANNER" class="ban_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<span class="m-text9 p-t-45 fs-20-sm">
								Stay Active
							</span>

							<br>
							

								<div class="wrap-btn-slide1 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite  trans-0-4">
								Shop Now
							</a>
						</div>

						</div>
					</div>
				</div>

			
			</div>
		</div>
	</section>
	<!-- ------------------Banner2  start ------------------------>

	<!-- ------------------Banner4  start ------------------------>
<!-- Slide1 -->

<style>
	.slide1 button:hover{
		background-color: white !important;
		color: black;
	}
</style>
<br><br>
<section class="slide1">

	
	<div class="wrap-slick2">
		<div class="slick1">
			
		
	
			

			<div class="item-slick1 item2-slick1" style="background-image: url('https://static.nike.com/a/images/f_auto/dpr_2.0/w_1407,c_limit/a01665bf-08e7-4d5d-8fb6-841382e3f900/nike-just-do-it.jpg');">
					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
						<span class="caption1-slide1 m-text1 t-center   m-b-15" data-appear="rollIn">
							Nike ZoomX Vaporfly NEXT%
						</span>
						<h2 class="caption2-slide1 xl-text1 t-center   m-b-37" data-appear="lightSpeedIn">
							FAST IS BACK
						</h2>
						<div class="wrap-btn-slide1 w-size1 " data-appear="slideInUp">
							
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
								Shop Now
							</a>
						</div>
					</div>
				</div>

		</div>
	</div>
</section>

<!-- ------------------Banner4  end ------------------------>

	<!-- ------------------Banner3  start ------------------------>

	<section class="banner2 bg5 p-t-55 p-b-55">
		<h4 style="font-weight: 500;">Training's Essentials</h4>
		<div class="">
			<div class="row">
				<div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_700,c_limit/24fb4f53-ba07-46fa-934e-bcb35b0cc021/nike-just-do-it.jpg" alt="IMG-BANNER" class="ban_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<span class="m-text9 p-t-45 fs-20-sm">
								SuperRe Go
							</span>

							<br>
							

								<div class="wrap-btn-slide1 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite  trans-0-4">
								Shop Now
							</a>
						</div>

						</div>
					</div>
				</div>

				<div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_700,c_limit/f33275db-0cbb-406a-8ac9-430ff07433b7/nike-just-do-it.jpg"  alt="IMG-BANNER" class="ban_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<span class="m-text9 p-t-45 fs-20-sm" style="color: black;">
								Bras and Leggings
							</span>

							<br>
							

								<div class="wrap-btn-slide2 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2  trans-0-4" style="background-color: black; color:white;">
								Shop Now
							</a>
						</div>

						</div>
					</div>
				</div>

			
			</div>
		</div>
	</section>
	<!-- ------------------Banner3  end ------------------------>

	<!-- ------------------Banner5  start ------------------------>

	<section class="banner2 bg5 p-t-55 p-b-55">
		<h4 style="font-weight: 500;">More Products</h4>
		<div class="">
			<div class="row">
				<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_573,c_limit/0bafb728-2ae2-416f-bb18-5935801c8071/nike-just-do-it.png" alt="IMG-BANNER" class="ban5_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<br><br><br><br><br>
						
							

							<br>
							

								<div class="wrap-btn-slide1 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite  trans-0-4">
								Men's
							</a>
						</div>

						</div>
					</div>
				</div>

				<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_573,c_limit/2c8754ce-6287-4e77-a198-1ad483fba257/nike-just-do-it.png" alt="IMG-BANNER" class="ban5_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<br><br><br><br><br>

							<br>
							

								<div class="wrap-btn-slide1 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite  trans-0-4">
								Women's
							</a>
						</div>

						</div>
					</div>
				</div>

				<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto p-t-15 p-b-15">
					<div class="pos-relative">
						<img src="https://static.nike.com/a/images/f_auto/dpr_2.0/h_573,c_limit/414db494-7ebc-4d53-bbff-58d50b380a24/nike-just-do-it.png" alt="IMG-BANNER" class="ban5_img">

						<div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
							<br><br><br><br><br>
							<br><br><br><br><br>
							<br><br><br><br><br>

							<br>
							

								<div class="wrap-btn-slide1 w-size1 animated" data-appear="slideInUp">
						
							<a href="/shop/" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite  trans-0-4">
								Kids'
							</a>
						</div>

						</div>
					</div>
				</div>
			
			</div>
		</div>
	</section>
	<!-- ------------------Banner2  start ------------------------>


	
	

	<!-- Shipping -->
	<section class="shipping bgwhite p-t-62 p-b-46">
		<div class="flex-w p-l-15 p-r-15">
			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
				<h4 class="m-text12 t-center">
					Free Delivery Worldwide
				</h4>

				<a href="#" class="s-text11 t-center">
					Click here for more info
				</a>
			</div>

			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 bo2 respon2">
				<h4 class="m-text12 t-center">
					30 Days Return
				</h4>

				<span class="s-text11 t-center">
					Simply return it within 30 days for an exchange.
				</span>
			</div>

			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
				<h4 class="m-text12 t-center">
					Store Opening
				</h4>

				<span class="s-text11 t-center">
					Shop open from Monday to Sunday
				</span>
			</div>
		</div>
	</section>




	

	{% endblock content %}


	

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>
              {% else %}
                  ${{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ${{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}